name: f Build

on:
  workflow_dispatch:
  push:
    branches:
      - f
jobs:
  f-build:
    name: f Build
    runs-on: windows-2022
    env:
      FRIDA_VERSION: "16.5.6"
      FRIDA_PREFIX: "C:\\frida-build"
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup dependencies
        run: |
          cd C:\ ; git clone --depth=1 --recurse-submodules https://github.com/frida/frida.git -b ${{ env.FRIDA_VERSION }}
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build
        run: |
          cd C:\frida ; 
          .\configure.bat --prefix=${{ env.FRIDA_PREFIX }} --host=windows-x86_64 --enable-shared --enable-gadget --enable-server --enable-portal --enable-inject -- "-Dfrida_qml=auto" "-Dfrida-gum:devkits=gum,gumjs" "-Dfrida-core:devkits=core"
          .\make
          .\make install
          ls C:\frida-build
      - name: Package Directories
        run: |
          7z a frida-win-x64-devkits_core.7z ${{ env.FRIDA_PREFIX }}/lib/frida/devkits/core/
      - uses: actions/upload-artifact@v4
        with:
          name: frida-win-x64-devkits_core
          path: frida-win-x64-devkits_core.7z
      # - name: Update modfda Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: 
      #     body: 'Frida '
      #     files: |
      #       
  f-mini-build:
    name: f mini Build
    runs-on: windows-2022
    env:
      FRIDA_VERSION: "16.5.6"
      FRIDA_PREFIX: "C:\\frida-build"
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup dependencies
        run: |
          cd C:\ ; git clone --depth=1 --recurse-submodules https://github.com/frida/frida.git -b ${{ env.FRIDA_VERSION }}
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build
        run: |
          cd C:\frida ; 
          .\configure.bat --prefix=${{ env.FRIDA_PREFIX }} --host=windows-x86_64 --enable-shared -- "-Dfrida-gum:devkits=gum,gumjs" "-Dfrida-core:devkits=core"
          .\make
          .\make install
          ls C:\frida-build
      - name: Package Directories
        run: |
          7z a frida-win-x64-devkits_core.7z ${{ env.FRIDA_PREFIX }}/lib/frida/devkits/core/
      - uses: actions/upload-artifact@v4
        with:
          name: frida-win-x64-devkits_core
          path: frida-win-x64-devkits_core.7z
      # - name: Update modfda Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: 
      #     body: 'Frida '
      #     files: |
      #       