name: llvm Build

on:
  workflow_dispatch:
  push:
    branches:
      - zig
jobs:
  # llvm-build:
  #   name: llvm Build
  #   runs-on: windows-2022
  #   steps:
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: amd64
  #     - name: Prepare
  #       run: |
  #         # choco install wget
  #         # cd C:\
  #         # wget https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/clang-19.1.7.src.tar.xz
  #         # wget https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/llvm-19.1.7.src.tar.xz
  #         # wget https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/lld-19.1.7.src.tar.xz
  #         # ls
  #         # 7z x C:\clang-19.1.7.src.tar.xz -oC:\
  #         # 7z x C:\clang-19.1.7.src.tar -oC:\
  #         # rm C:\clang-19.1.7.src.tar.xz ; rm C:\clang-19.1.7.src.tar
  #         # ls
  #         # 7z x C:\llvm-19.1.7.src.tar.xz -oC:\
  #         # 7z x C:\llvm-19.1.7.src.tar -oC:\
  #         # rm C:\llvm-19.1.7.src.tar.xz ; rm C:\llvm-19.1.7.src.tar
  #         # 7z x C:\lld-19.1.7.src.tar.xz -oC:\
  #         # 7z x C:\lld-19.1.7.src.tar -oC:\
  #         # rm C:\lld-19.1.7.src.tar.xz ; rm C:\lld-19.1.7.src.tar
  #         # mkdir C:\llvm-19.1.7.src\build-release ; cd C:\llvm-19.1.7.src\build-release
  #         # cmake.exe .. -G Ninja -DCMAKE_INSTALL_PREFIX=C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt -DCMAKE_PREFIX_PATH=C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt -DLLVM_ENABLE_ZLIB=OFF -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_LIBXML2=OFF -DLLVM_USE_CRT_RELEASE=MT
  #         # ninja ; ninja install
  #         # mkdir C:\lld-19.1.7.src\build-release ; cd C:\lld-19.1.7.src\build-release
  #         # cmake.exe .. -G Ninja -DCMAKE_INSTALL_PREFIX=C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt -DCMAKE_PREFIX_PATH=C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_CRT_RELEASE=MT
  #         # ninja ; ninja install
  #         # mkdir C:\clang-19.1.7.src\build-release ; cd C:\clang-19.1.7.src\build-release
  #         # cmake.exe .. -G Ninja -DCMAKE_INSTALL_PREFIX=C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt -DCMAKE_PREFIX_PATH=C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_CRT_RELEASE=MT
  #         # ninja ; ninja install
  #         cd C:\
  #         git clone --depth 1 --branch release/19.x https://github.com/llvm/llvm-project llvm-project-19
  #         cd llvm-project-19
  #         git checkout release/19.x
  #         mkdir build-release
  #         cd build-release
  #         cmake ..\llvm -DCMAKE_INSTALL_PREFIX="C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="lld;clang" -DLLVM_ENABLE_LIBXML2=OFF -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_ENABLE_LIBEDIT=OFF -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_PARALLEL_LINK_JOBS=1 -DLLVM_USE_CRT_RELEASE=MT -GNinja
  #         ninja install
  #     - name: Pack llvm
  #       run: |
  #         7z a C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt.7z C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: llvm
  #         path: C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt.7z
  #     - name: Update llvm Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         tag_name: zig-build
  #         files: |
  #           C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt.7z
  # gen-compilation-database-master-patch-build:
  #   name: zig Build
  #   runs-on: windows-2022
  #   steps:
  #     - name: Prepare
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         choco install wget
  #         cd C:\ ; git clone --depth 1 https://github.com/ziglang/zig ; cd zig
  #         wget -q https://github.com/gxiGpf/build/releases/download/zig-build/Support-generating-JSON-compilation-database.patch
  #         git apply Support-generating-JSON-compilation-database.patch
  #         7z a C:\Support-generating-JSON-compilation-database-files.7z C:\zig\lib\std\Build.zig C:\zig\lib\std\Build\Step\Compile.zig
  #     - name: Update zig Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         tag_name: zig-build
  #         files: |
  #           C:\Support-generating-JSON-compilation-database-files.7z
  zig-build:
    name: zig Build
    runs-on: windows-2022
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Prepare
        run: |
          choco install wget
          cd C:\ ; wget -q https://github.com/gxiGpf/build/releases/download/zig-build/llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt.7z
          7z x C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt.7z -oC:\ ; rm C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt.7z
      - name: Prepare
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd C:\ ; git clone --depth 1 https://github.com/ziglang/zig ; cd zig
          wget -q https://github.com/gxiGpf/build/releases/download/zig-build/Support-generating-JSON-compilation-database.mini.patch
          git apply Support-generating-JSON-compilation-database.mini.patch
          mkdir build ; cd build
          cmake .. -Thost=x64 -A x64 -DCMAKE_PREFIX_PATH=C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\zig-release
          msbuild -p:Configuration=Release INSTALL.vcxproj
          ls
          # cmake .. -GNinja -DCMAKE_PREFIX_PATH="C:\llvm+clang+lld-19.1.7-x86_64-windows-msvc-release-mt" -DCMAKE_BUILD_TYPE=Release
          # ninja
          # ls
      # - name: Pack
      #   run: |
      #     7z a C:\zig-custom-master.7z C:\zig-release
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: zig
      #     path: C:\zig-custom-master.7z
      # - name: Update llvm Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: zig-build
      #     files: |
      #       C:\Support-generating-JSON-compilation-database.patch