name: freetype Build

on:
  workflow_dispatch:
  push:
    branches:
      - freetype
jobs:
  freetype-build:
    name: freetype Build
    runs-on: windows-2022
    steps:
      - name: Set Deps
        env:
          FreeType2_Release_URL: "https://github.com/gxiGpf/build/releases/download/src/freetype-2.13.2.tar.xz"
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('${{ env.FreeType2_Release_URL }}','freetype.tar.xz')
          7z x freetype.tar.xz -so | 7z x -si -ttar -oC:\ ; rm freetype.tar.xz
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build
        env:
          FreeType2_DIR_NAME: "freetype-2.13.2"
        run: |
          cd C:\${{ env.FreeType2_DIR_NAME }} ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\freetype_install -DBUILD_SHARED_LIBS=ON
          ninja ; ninja install
          7z a C:\freetype_shared_release.7z C:\freetype_install
      - uses: actions/upload-artifact@v4
        with:
          name: FreeType2 Release Shared
          path: C:\freetype_shared_release.7z
      - name: Update freetype Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: freetype-build
          files: |
            C:\freetype_shared_release.7z

  freetype-harfbuzz-build:
    name: freetype harfbuzz Build
    runs-on: windows-2022
    steps:
      - name: Set Deps
        env:
          FreeType2_Release_URL: "https://github.com/gxiGpf/build/releases/download/src/freetype-2.13.2.tar.xz"
          HarfBuzz_GIT_URL: "https://github.com/harfbuzz/harfbuzz"
          HarfBuzz_LATEST_RELEASE_VERSION: "9.0.0"
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('${{ env.FreeType2_Release_URL }}','freetype.tar.xz')
          7z x freetype.tar.xz -so | 7z x -si -ttar -oC:\ ; rm freetype.tar.xz
          cd C:\ ; git clone --depth=1 ${{ env.HarfBuzz_GIT_URL }} -b ${{ env.HarfBuzz_LATEST_RELEASE_VERSION }}
          pip3 install meson
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build
        env:
          FreeType2_DIR_NAME: "freetype-2.13.2"
        run: |
          $env:Path = "C:\harfbuzz_install;C:\harfbuzz_install\lib;C:\ninja;$env:Path"
          cd C:\harfbuzz ; meson build --wrap-mode=default --prefix=C:\harfbuzz_install
          cd C:\${{ env.FreeType2_DIR_NAME }} ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\freetype_install -DBUILD_SHARED_LIBS=ON -DFT_REQUIRE_HARFBUZZ=TRUE
          ninja ; ninja install
          7z a C:\freetype_with_harfbuzz_shared_release.7z C:\freetype_install
          7z a C:\harfbuzz_shared_release.7z C:\harfbuzz_install
      - uses: actions/upload-artifact@v4
        with:
          name: FreeType2 HarfBuzz Release Shared
          path: C:\freetype_with_harfbuzz_shared_release.7z
      - name: Update freetype Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: freetype-build
          files: |
            C:\freetype_with_harfbuzz_shared_release.7z
            C:\harfbuzz_shared_release.7z