name: harkrf Build

on:
  workflow_dispatch:
  push:
    branches:
      - harkrf
jobs:
  harkrf-vcpkg-build:
    name: harkrf vcpkg Build
    runs-on: windows-2022
    steps:
      - name: Set Deps
        env:
          harkrf_GIT_URL: "https://github.com/greatscottgadgets/hackrf"
          harkrf_LATEST_RELEASE_VERSION: "v2024.02.1"
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 ${{ env.harkrf_GIT_URL }} -b ${{ env.harkrf_LATEST_RELEASE_VERSION }}
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Update Vcpkg
        run: |
          cd C:\vcpkg ; git pull ; .\bootstrap-vcpkg.bat
          vcpkg install pthreads:x64-windows-static libusb:x64-windows-static fftw3:x64-windows-static
      - name: Build
        env:
          DEPS_INCLUDE_DIR: "C:\\vcpkg\\installed\\x64-windows\\include"
          DEPS_LIB_DIR: "C:\\vcpkg\\installed\\x64-windows\\lib"
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\harkrf ; mkdir build ; cd build
          cmake .. -GNinja -DLIBUSB_INCLUDE_DIR=${{env.DEPS_INCLUDE_DIR}} -DLIBUSB_LIBRARIES=${{env.DEPS_LIB_DIR}} -DTHREADS_PTHREADS_INCLUDE_DIR=${{env.DEPS_INCLUDE_DIR}} -DTHREADS_PTHREADS_WIN32_LIBRARY=${{env.DEPS_LIB_DIR}} -DFFTW_INCLUDES=${{env.DEPS_INCLUDE_DIR}} -DFFTW_LIBRARIES=${{env.DEPS_LIB_DIR}} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\harkrf_install -DBUILD_SHARED_LIBS=ON
          ninja ; ninja install
          7z a C:\harkrf_vcpkg_latest.7z C:\harkrf_install
      - uses: actions/upload-artifact@v4
        with:
          name: harkrf Release Shared
          path: C:\harkrf_vcpkg_latest.7z
      - name: Update harkrf Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: harkrf-build
          files: |
            C:\harkrf_vcpkg_latest.7z
