name: zls Build

on:
  workflow_dispatch:
jobs:
  zls-build:
    name: zls Build
    runs-on: windows-2022
    steps:
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build Pack Zls
        run: |
          cd C:\ ; git clone --depth=1 https://github.com/zigtools/zls
          cd zls ; zig build -Doptimize=ReleaseSafe
          7z a C:\zls_master_ReleaseSafe.7z C:\zls\zig-out\bin\zls.exe
          zig build -Doptimize=ReleaseFast
          7z a C:\zls_master_ReleaseFast.7z C:\zls\zig-out\bin\zls.exe
      - uses: actions/upload-artifact@v4
        with:
          name: zls_master_ReleaseSafe
          path: C:\zls_master_ReleaseSafe.7z
      - uses: actions/upload-artifact@v4
        with:
          name: zls_master_ReleaseFast
          path: C:\zls_master_ReleaseFast.7z
      - name: Update zls Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: zls-build
          files: |
            C:\zls_master_ReleaseSafe.7z
            C:\zls_master_ReleaseFast.7z