name: zed Build

on:
  workflow_dispatch:
  push:
    branches:
      - zed
jobs:
  zed-build:
    name: zed Build
    runs-on: windows-2022
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build Pack zed
        env: 
          LATEST_VERSION: "v0.195.0-pre"
        run: |
          git config --system core.longpaths true
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
          Install-Module -Name PSToml -Scope CurrentUser -Force
          cd C:\ ; git clone --depth=1 https://github.com/zed-industries/zed -b ${{ env.LATEST_VERSION }}
          cd zed
          Set-Content -Path ".cargo/config.toml" -Value @"
          [target."cfg(all())"]
          rustflags = ["--cfg",
          "windows_slim_errors",
          "-C",
          "target-feature=+crt-static"]
          [profile.release]
          debug = false
          "@
          rustup update ; rustup target add wasm32-wasip1
          cargo build --release
          7z a C:\zed_release.7z C:\zed\target\release\zed.exe
          ls target\release
      - uses: actions/upload-artifact@v4
        with:
          name: zed_release
          path: C:\zed_release.7z
      - name: Update zed Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: zed-build
          files: |
            C:\zed_release.7z
